added streak stats badge
Naereen/badges pull request #31
Opened 2021-03-26 17:48 UTC by hendrasob

added streak stats badge for this repo

2021-03-28 16:42 UTC, Naereen requested changes

2021-03-28 16:42 UTC, Naereen commented on README.md
> +[![Anurag's github streak](https://github-readme-streak-stats.herokuapp.com/?user=Naereen&theme=blue-green)](https://github.com/DenverCoder1/github-readme-streak-stats)
Please update `Anurag's` to `DenverCoder1's`, the author of this new badge app. Thanks!

2021-03-28 22:38 UTC, hendrasob commented
Done friends

2021-03-28 23:20 UTC, Naereen approved these changes
Great change, thanks! I'll merge.

2021-03-28 23:20 UTC, merged

2021-03-28 23:20 UTC, Naereen commented
Thanks again for the suggestion, and the modification, @hendrasob.

2021-03-28 23:48 UTC, hendrasob commented
Okay friend, you're welcome.

2021-03-29 06:13 UTC, Naereen commented
@hendrasob I just stumbled across your nice repo <https://github.com/hendrasob/badges>, if you want to add some of these nice badges to my (long) list, please feel free to submit a PR! I'll merge and be grateful :pray:! Regards from France, -- @Naereen

2021-03-29 08:18 UTC, hendrasob commented
@Naereen 🇫🇷 this a good idea. I also very happy and grateful for your idea 👍. I will definitely submit a PR for your repo! Regards from Indonesia ~ @hendrasob 🇮🇩

2021-03-29 08:24 UTC, Naereen commented
Thanks!